/// <reference path="../lib/openrct2.d.ts" />

// Auto-generated by openrct2-codegen 0.5.0
// OpenRCT2 v0.4.32 (API v110)
// Generated: 2026-03-30T15:33:35.935810+00:00
//
// DO NOT EDIT -- regenerate with: openrct2-codegen generate

/**
 * Execute a game action and reply with the standardised response envelope.
 *
 * On success:    { success: true,  payload: <GameActionResult> }
 * On game error: { success: false, error: "game_error", status: <int>, ... }
 */
function executeAndReply(actionName: string, params: object | undefined, reply: (response: object) => void): void {
    context.executeAction(actionName, params || {}, function (result) {
        if (result.error !== 0) {
            var response: any = {
                success: false,
                error: "game_error",
                status: result.error,
            };
            if (result.errorTitle) {
                response.title = result.errorTitle;
            }
            if (result.errorMessage) {
                response.message = result.errorMessage;
            }
            if (result.cost !== undefined) {
                response.cost = result.cost;
            }
            if (result.position) {
                response.position = result.position;
            }
            reply(response);
        } else {
            reply({ success: true, payload: result });
        }
    });
}

/**
 * Handle game action endpoints.
 *
 * Returns true if the endpoint was handled, false otherwise.
 * 81 actions from OpenRCT2 v0.4.32.
 */
export function handleActions(endpoint: string, params: object | undefined, reply: (response: object) => void): boolean {
    switch (endpoint) {
        case "balloonpress":
        case "bannerplace":
        case "bannerremove":
        case "bannersetcolour":
        case "bannersetname":
        case "bannersetstyle":
        case "cheatset":
        case "clearscenery":
        case "footpathadditionplace":
        case "footpathadditionremove":
        case "footpathlayoutplace":
        case "footpathplace":
        case "footpathremove":
        case "gamesetspeed":
        case "guestsetflags":
        case "guestsetname":
        case "landbuyrights":
        case "landlower":
        case "landraise":
        case "landsetheight":
        case "landsetrights":
        case "landsmooth":
        case "largesceneryplace":
        case "largesceneryremove":
        case "largescenerysetcolour":
        case "loadorquit":
        case "mapchangesize":
        case "mazeplacetrack":
        case "mazesettrack":
        case "networkmodifygroup":
        case "parkentranceplace":
        case "parkentranceremove":
        case "parkmarketing":
        case "parksetdate":
        case "parksetentrancefee":
        case "parksetloan":
        case "parksetname":
        case "parksetparameter":
        case "parksetresearchfunding":
        case "pausetoggle":
        case "peeppickup":
        case "peepspawnplace":
        case "playerkick":
        case "playersetgroup":
        case "ridecreate":
        case "ridedemolish":
        case "rideentranceexitplace":
        case "rideentranceexitremove":
        case "ridefreezerating":
        case "ridesetappearance":
        case "ridesetcolourscheme":
        case "ridesetname":
        case "ridesetprice":
        case "ridesetsetting":
        case "ridesetstatus":
        case "ridesetvehicle":
        case "scenariosetsetting":
        case "signsetname":
        case "signsetstyle":
        case "smallsceneryplace":
        case "smallsceneryremove":
        case "smallscenerysetcolour":
        case "stafffire":
        case "staffhire":
        case "staffsetcolour":
        case "staffsetcostume":
        case "staffsetname":
        case "staffsetorders":
        case "staffsetpatrolarea":
        case "surfacesetstyle":
        case "tilemodify":
        case "trackdesign":
        case "trackplace":
        case "trackremove":
        case "tracksetbrakespeed":
        case "wallplace":
        case "wallremove":
        case "wallsetcolour":
        case "waterlower":
        case "waterraise":
        case "watersetheight":
            executeAndReply(endpoint, params, reply);
            return true;
        default:
            return false;
    }
}
