/// <reference path="../lib/openrct2.d.ts" />

// Auto-generated by openrct2-codegen 0.7.3
// OpenRCT2 v0.4.32 (API v110)
// Generated: 2026-04-01T16:26:03.023423+00:00
//
// DO NOT EDIT -- regenerate with: openrct2-codegen generate

// ── Interface serializers (union variants) ───────────────────────────────────

function serializeRideResearchItem(item: RideResearchItem): object {
    return {
        type: item.type,
        category: item.category,
        rideType: item.rideType,
        object: item.object,
    };
}

function serializeSceneryResearchItem(item: SceneryResearchItem): object {
    return {
        category: item.category,
        type: item.type,
        object: item.object,
    };
}

function serializeHandyman(item: Handyman): object {
    var flags: any = {};
    flags["leavingPark"] = item.getFlag("leavingPark");
    flags["slowWalk"] = item.getFlag("slowWalk");
    flags["tracking"] = item.getFlag("tracking");
    flags["waving"] = item.getFlag("waving");
    flags["hasPaidForParkEntry"] = item.getFlag("hasPaidForParkEntry");
    flags["photo"] = item.getFlag("photo");
    flags["painting"] = item.getFlag("painting");
    flags["wow"] = item.getFlag("wow");
    flags["litter"] = item.getFlag("litter");
    flags["lost"] = item.getFlag("lost");
    flags["hunger"] = item.getFlag("hunger");
    flags["toilet"] = item.getFlag("toilet");
    flags["crowded"] = item.getFlag("crowded");
    flags["happiness"] = item.getFlag("happiness");
    flags["nausea"] = item.getFlag("nausea");
    flags["purple"] = item.getFlag("purple");
    flags["pizza"] = item.getFlag("pizza");
    flags["explode"] = item.getFlag("explode");
    flags["rideShouldBeMarkedAsFavourite"] = item.getFlag("rideShouldBeMarkedAsFavourite");
    flags["parkEntranceChosen"] = item.getFlag("parkEntranceChosen");
    flags["contagious"] = item.getFlag("contagious");
    flags["joy"] = item.getFlag("joy");
    flags["angry"] = item.getFlag("angry");
    flags["iceCream"] = item.getFlag("iceCream");
    flags["hereWeAre"] = item.getFlag("hereWeAre");
    flags["positionFrozen"] = item.getFlag("positionFrozen");
    flags["animationFrozen"] = item.getFlag("animationFrozen");
    return {
        id: item.id !== undefined ? item.id : null,
        type: item.type,
        x: item.x,
        y: item.y,
        z: item.z,
        flags: flags,
        peepType: item.peepType,
        name: item.name,
        destination: serializeCoordsXY(item.destination),
        direction: item.direction,
        energy: item.energy,
        energyTarget: item.energyTarget,
        staffType: item.staffType,
        colour: item.colour,
        availableCostumes: item.availableCostumes,
        costume: item.costume,
        orders: item.orders,
        patrolArea: serializePatrolArea(item.patrolArea),
        availableAnimations: item.availableAnimations,
        animation: item.animation,
        animationOffset: item.animationOffset,
        animationLength: item.animationLength,
        lawnsMown: item.lawnsMown,
        gardensWatered: item.gardensWatered,
        litterSwept: item.litterSwept,
        binsEmptied: item.binsEmptied,
    };
}

function serializeMechanic(item: Mechanic): object {
    var flags: any = {};
    flags["leavingPark"] = item.getFlag("leavingPark");
    flags["slowWalk"] = item.getFlag("slowWalk");
    flags["tracking"] = item.getFlag("tracking");
    flags["waving"] = item.getFlag("waving");
    flags["hasPaidForParkEntry"] = item.getFlag("hasPaidForParkEntry");
    flags["photo"] = item.getFlag("photo");
    flags["painting"] = item.getFlag("painting");
    flags["wow"] = item.getFlag("wow");
    flags["litter"] = item.getFlag("litter");
    flags["lost"] = item.getFlag("lost");
    flags["hunger"] = item.getFlag("hunger");
    flags["toilet"] = item.getFlag("toilet");
    flags["crowded"] = item.getFlag("crowded");
    flags["happiness"] = item.getFlag("happiness");
    flags["nausea"] = item.getFlag("nausea");
    flags["purple"] = item.getFlag("purple");
    flags["pizza"] = item.getFlag("pizza");
    flags["explode"] = item.getFlag("explode");
    flags["rideShouldBeMarkedAsFavourite"] = item.getFlag("rideShouldBeMarkedAsFavourite");
    flags["parkEntranceChosen"] = item.getFlag("parkEntranceChosen");
    flags["contagious"] = item.getFlag("contagious");
    flags["joy"] = item.getFlag("joy");
    flags["angry"] = item.getFlag("angry");
    flags["iceCream"] = item.getFlag("iceCream");
    flags["hereWeAre"] = item.getFlag("hereWeAre");
    flags["positionFrozen"] = item.getFlag("positionFrozen");
    flags["animationFrozen"] = item.getFlag("animationFrozen");
    return {
        id: item.id !== undefined ? item.id : null,
        type: item.type,
        x: item.x,
        y: item.y,
        z: item.z,
        flags: flags,
        peepType: item.peepType,
        name: item.name,
        destination: serializeCoordsXY(item.destination),
        direction: item.direction,
        energy: item.energy,
        energyTarget: item.energyTarget,
        staffType: item.staffType,
        colour: item.colour,
        availableCostumes: item.availableCostumes,
        costume: item.costume,
        orders: item.orders,
        patrolArea: serializePatrolArea(item.patrolArea),
        availableAnimations: item.availableAnimations,
        animation: item.animation,
        animationOffset: item.animationOffset,
        animationLength: item.animationLength,
        ridesFixed: item.ridesFixed,
        ridesInspected: item.ridesInspected,
    };
}

function serializeSecurity(item: Security): object {
    var flags: any = {};
    flags["leavingPark"] = item.getFlag("leavingPark");
    flags["slowWalk"] = item.getFlag("slowWalk");
    flags["tracking"] = item.getFlag("tracking");
    flags["waving"] = item.getFlag("waving");
    flags["hasPaidForParkEntry"] = item.getFlag("hasPaidForParkEntry");
    flags["photo"] = item.getFlag("photo");
    flags["painting"] = item.getFlag("painting");
    flags["wow"] = item.getFlag("wow");
    flags["litter"] = item.getFlag("litter");
    flags["lost"] = item.getFlag("lost");
    flags["hunger"] = item.getFlag("hunger");
    flags["toilet"] = item.getFlag("toilet");
    flags["crowded"] = item.getFlag("crowded");
    flags["happiness"] = item.getFlag("happiness");
    flags["nausea"] = item.getFlag("nausea");
    flags["purple"] = item.getFlag("purple");
    flags["pizza"] = item.getFlag("pizza");
    flags["explode"] = item.getFlag("explode");
    flags["rideShouldBeMarkedAsFavourite"] = item.getFlag("rideShouldBeMarkedAsFavourite");
    flags["parkEntranceChosen"] = item.getFlag("parkEntranceChosen");
    flags["contagious"] = item.getFlag("contagious");
    flags["joy"] = item.getFlag("joy");
    flags["angry"] = item.getFlag("angry");
    flags["iceCream"] = item.getFlag("iceCream");
    flags["hereWeAre"] = item.getFlag("hereWeAre");
    flags["positionFrozen"] = item.getFlag("positionFrozen");
    flags["animationFrozen"] = item.getFlag("animationFrozen");
    return {
        id: item.id !== undefined ? item.id : null,
        type: item.type,
        x: item.x,
        y: item.y,
        z: item.z,
        flags: flags,
        peepType: item.peepType,
        name: item.name,
        destination: serializeCoordsXY(item.destination),
        direction: item.direction,
        energy: item.energy,
        energyTarget: item.energyTarget,
        staffType: item.staffType,
        colour: item.colour,
        availableCostumes: item.availableCostumes,
        costume: item.costume,
        orders: item.orders,
        patrolArea: serializePatrolArea(item.patrolArea),
        availableAnimations: item.availableAnimations,
        animation: item.animation,
        animationOffset: item.animationOffset,
        animationLength: item.animationLength,
        vandalsStopped: item.vandalsStopped,
    };
}

function serializeEntertainer(item: Entertainer): object {
    var flags: any = {};
    flags["leavingPark"] = item.getFlag("leavingPark");
    flags["slowWalk"] = item.getFlag("slowWalk");
    flags["tracking"] = item.getFlag("tracking");
    flags["waving"] = item.getFlag("waving");
    flags["hasPaidForParkEntry"] = item.getFlag("hasPaidForParkEntry");
    flags["photo"] = item.getFlag("photo");
    flags["painting"] = item.getFlag("painting");
    flags["wow"] = item.getFlag("wow");
    flags["litter"] = item.getFlag("litter");
    flags["lost"] = item.getFlag("lost");
    flags["hunger"] = item.getFlag("hunger");
    flags["toilet"] = item.getFlag("toilet");
    flags["crowded"] = item.getFlag("crowded");
    flags["happiness"] = item.getFlag("happiness");
    flags["nausea"] = item.getFlag("nausea");
    flags["purple"] = item.getFlag("purple");
    flags["pizza"] = item.getFlag("pizza");
    flags["explode"] = item.getFlag("explode");
    flags["rideShouldBeMarkedAsFavourite"] = item.getFlag("rideShouldBeMarkedAsFavourite");
    flags["parkEntranceChosen"] = item.getFlag("parkEntranceChosen");
    flags["contagious"] = item.getFlag("contagious");
    flags["joy"] = item.getFlag("joy");
    flags["angry"] = item.getFlag("angry");
    flags["iceCream"] = item.getFlag("iceCream");
    flags["hereWeAre"] = item.getFlag("hereWeAre");
    flags["positionFrozen"] = item.getFlag("positionFrozen");
    flags["animationFrozen"] = item.getFlag("animationFrozen");
    return {
        id: item.id !== undefined ? item.id : null,
        type: item.type,
        x: item.x,
        y: item.y,
        z: item.z,
        flags: flags,
        peepType: item.peepType,
        name: item.name,
        destination: serializeCoordsXY(item.destination),
        direction: item.direction,
        energy: item.energy,
        energyTarget: item.energyTarget,
        staffType: item.staffType,
        colour: item.colour,
        availableCostumes: item.availableCostumes,
        costume: item.costume,
        orders: item.orders,
        patrolArea: serializePatrolArea(item.patrolArea),
        availableAnimations: item.availableAnimations,
        animation: item.animation,
        animationOffset: item.animationOffset,
        animationLength: item.animationLength,
    };
}

function serializeSurfaceElement(item: SurfaceElement): object {
    return {
        type: item.type,
        baseHeight: item.baseHeight,
        baseZ: item.baseZ,
        clearanceHeight: item.clearanceHeight,
        clearanceZ: item.clearanceZ,
        occupiedQuadrants: item.occupiedQuadrants,
        isGhost: item.isGhost,
        isHidden: item.isHidden,
        slope: item.slope,
        surfaceStyle: item.surfaceStyle,
        edgeStyle: item.edgeStyle,
        waterHeight: item.waterHeight,
        grassLength: item.grassLength,
        ownership: item.ownership,
        parkFences: item.parkFences,
        hasOwnership: item.hasOwnership,
        hasConstructionRights: item.hasConstructionRights,
    };
}

function serializeFootpathElement(item: FootpathElement): object {
    return {
        type: item.type,
        baseHeight: item.baseHeight,
        baseZ: item.baseZ,
        clearanceHeight: item.clearanceHeight,
        clearanceZ: item.clearanceZ,
        occupiedQuadrants: item.occupiedQuadrants,
        isGhost: item.isGhost,
        isHidden: item.isHidden,
        object: item.object !== undefined ? item.object : null,
        surfaceObject: item.surfaceObject !== undefined ? item.surfaceObject : null,
        railingsObject: item.railingsObject !== undefined ? item.railingsObject : null,
        edges: item.edges,
        corners: item.corners,
        slopeDirection: item.slopeDirection !== undefined ? item.slopeDirection : null,
        isBlockedByVehicle: item.isBlockedByVehicle,
        isWide: item.isWide,
        isQueue: item.isQueue,
        queueBannerDirection: item.queueBannerDirection !== undefined ? item.queueBannerDirection : null,
        ride: item.ride !== undefined ? item.ride : null,
        station: item.station !== undefined ? item.station : null,
        addition: item.addition !== undefined ? item.addition : null,
        additionStatus: item.additionStatus !== undefined ? item.additionStatus : null,
        isAdditionBroken: item.isAdditionBroken !== undefined ? item.isAdditionBroken : null,
        isAdditionGhost: item.isAdditionGhost !== undefined ? item.isAdditionGhost : null,
    };
}

function serializeTrackElement(item: TrackElement): object {
    return {
        type: item.type,
        baseHeight: item.baseHeight,
        baseZ: item.baseZ,
        clearanceHeight: item.clearanceHeight,
        clearanceZ: item.clearanceZ,
        occupiedQuadrants: item.occupiedQuadrants,
        isGhost: item.isGhost,
        isHidden: item.isHidden,
        direction: item.direction,
        trackType: item.trackType,
        rideType: item.rideType,
        sequence: item.sequence !== undefined ? item.sequence : null,
        mazeEntry: item.mazeEntry !== undefined ? item.mazeEntry : null,
        colourScheme: item.colourScheme !== undefined ? item.colourScheme : null,
        seatRotation: item.seatRotation !== undefined ? item.seatRotation : null,
        ride: item.ride,
        station: item.station !== undefined ? item.station : null,
        brakeBoosterSpeed: item.brakeBoosterSpeed !== undefined ? item.brakeBoosterSpeed : null,
        hasChainLift: item.hasChainLift,
        isInverted: item.isInverted,
        hasCableLift: item.hasCableLift,
        isHighlighted: item.isHighlighted,
    };
}

function serializeSmallSceneryElement(item: SmallSceneryElement): object {
    return {
        type: item.type,
        baseHeight: item.baseHeight,
        baseZ: item.baseZ,
        clearanceHeight: item.clearanceHeight,
        clearanceZ: item.clearanceZ,
        occupiedQuadrants: item.occupiedQuadrants,
        isGhost: item.isGhost,
        isHidden: item.isHidden,
        direction: item.direction,
        object: item.object,
        primaryColour: item.primaryColour,
        secondaryColour: item.secondaryColour,
        tertiaryColour: item.tertiaryColour,
        quadrant: item.quadrant,
        age: item.age,
    };
}

function serializeWallElement(item: WallElement): object {
    return {
        type: item.type,
        baseHeight: item.baseHeight,
        baseZ: item.baseZ,
        clearanceHeight: item.clearanceHeight,
        clearanceZ: item.clearanceZ,
        occupiedQuadrants: item.occupiedQuadrants,
        isGhost: item.isGhost,
        isHidden: item.isHidden,
        direction: item.direction,
        object: item.object,
        primaryColour: item.primaryColour,
        secondaryColour: item.secondaryColour,
        tertiaryColour: item.tertiaryColour,
        slope: item.slope,
        bannerIndex: item.bannerIndex !== undefined ? item.bannerIndex : null,
        bannerText: item.bannerText !== undefined ? item.bannerText : null,
    };
}

function serializeEntranceElement(item: EntranceElement): object {
    return {
        type: item.type,
        baseHeight: item.baseHeight,
        baseZ: item.baseZ,
        clearanceHeight: item.clearanceHeight,
        clearanceZ: item.clearanceZ,
        occupiedQuadrants: item.occupiedQuadrants,
        isGhost: item.isGhost,
        isHidden: item.isHidden,
        direction: item.direction,
        object: item.object,
        ride: item.ride,
        station: item.station,
        sequence: item.sequence,
        footpathObject: item.footpathObject !== undefined ? item.footpathObject : null,
        footpathSurfaceObject: item.footpathSurfaceObject !== undefined ? item.footpathSurfaceObject : null,
    };
}

function serializeLargeSceneryElement(item: LargeSceneryElement): object {
    return {
        type: item.type,
        baseHeight: item.baseHeight,
        baseZ: item.baseZ,
        clearanceHeight: item.clearanceHeight,
        clearanceZ: item.clearanceZ,
        occupiedQuadrants: item.occupiedQuadrants,
        isGhost: item.isGhost,
        isHidden: item.isHidden,
        direction: item.direction,
        object: item.object,
        primaryColour: item.primaryColour,
        secondaryColour: item.secondaryColour,
        tertiaryColour: item.tertiaryColour,
        sequence: item.sequence,
        bannerIndex: item.bannerIndex !== undefined ? item.bannerIndex : null,
        bannerText: item.bannerText !== undefined ? item.bannerText : null,
    };
}

function serializeBannerElement(item: BannerElement): object {
    return {
        type: item.type,
        baseHeight: item.baseHeight,
        baseZ: item.baseZ,
        clearanceHeight: item.clearanceHeight,
        clearanceZ: item.clearanceZ,
        occupiedQuadrants: item.occupiedQuadrants,
        isGhost: item.isGhost,
        isHidden: item.isHidden,
        direction: item.direction,
        object: item.object,
        primaryColour: item.primaryColour,
        secondaryColour: item.secondaryColour,
        bannerIndex: item.bannerIndex,
        bannerText: item.bannerText,
        isNoEntry: item.isNoEntry,
    };
}

// ── Union serializers ────────────────────────────────────────────────────────

export function serializeTileElement(item: TileElement): object {
    if (item.type === "surface") {
        return serializeSurfaceElement(item as SurfaceElement);
    } else if (item.type === "footpath") {
        return serializeFootpathElement(item as FootpathElement);
    } else if (item.type === "track") {
        return serializeTrackElement(item as TrackElement);
    } else if (item.type === "small_scenery") {
        return serializeSmallSceneryElement(item as SmallSceneryElement);
    } else if (item.type === "wall") {
        return serializeWallElement(item as WallElement);
    } else if (item.type === "entrance") {
        return serializeEntranceElement(item as EntranceElement);
    } else if (item.type === "large_scenery") {
        return serializeLargeSceneryElement(item as LargeSceneryElement);
    } else {
        return serializeBannerElement(item as BannerElement);
    }
}

export function serializeStaff(item: Staff): object {
    if (item.staffType === "handyman") {
        return serializeHandyman(item as Handyman);
    } else if (item.staffType === "mechanic") {
        return serializeMechanic(item as Mechanic);
    } else if (item.staffType === "security") {
        return serializeSecurity(item as Security);
    } else {
        return serializeEntertainer(item as Entertainer);
    }
}

export function serializeResearchItem(item: ResearchItem): object {
    if (item.type === "ride") {
        return serializeRideResearchItem(item as RideResearchItem);
    } else {
        return serializeSceneryResearchItem(item as SceneryResearchItem);
    }
}

// ── Interface serializers ────────────────────────────────────────────────────

function serializeResearch(item: Research): object {
    var inventedItems: object[] = [];
    for (var i_inventedItems = 0; i_inventedItems < item.inventedItems.length; i_inventedItems++) {
        inventedItems.push(serializeResearchItem(item.inventedItems[i_inventedItems]));
    }
    var uninventedItems: object[] = [];
    for (var i_uninventedItems = 0; i_uninventedItems < item.uninventedItems.length; i_uninventedItems++) {
        uninventedItems.push(serializeResearchItem(item.uninventedItems[i_uninventedItems]));
    }
    return {
        inventedItems: inventedItems,
        uninventedItems: uninventedItems,
        lastResearchedItem: item.lastResearchedItem !== null ? serializeResearchItem(item.lastResearchedItem as ResearchItem) : null,
        expectedItem: item.expectedItem !== null ? serializeResearchItem(item.expectedItem as ResearchItem) : null,
        funding: item.funding,
        priorities: item.priorities,
        stage: item.stage,
        progress: item.progress,
        expectedMonth: item.expectedMonth !== undefined ? item.expectedMonth : null,
        expectedDay: item.expectedDay !== undefined ? item.expectedDay : null,
    };
}

function serializeParkMessage(item: ParkMessage): object {
    return {
        isArchived: item.isArchived,
        month: item.month,
        day: item.day,
        tickCount: item.tickCount,
        type: item.type,
        text: item.text,
        subject: item.subject !== undefined ? item.subject : null,
    };
}

function serializeAward(item: Award): object {
    return {
        type: item.type,
        text: item.text,
        monthsRemaining: item.monthsRemaining,
        imageId: item.imageId,
        positive: item.positive,
    };
}

function serializeScenarioObjective(item: ScenarioObjective): object {
    return {
        type: item.type,
        guests: item.guests !== undefined ? item.guests : null,
        year: item.year !== undefined ? item.year : null,
        length: item.length !== undefined ? item.length : null,
        excitement: item.excitement !== undefined ? item.excitement : null,
        parkValue: item.parkValue !== undefined ? item.parkValue : null,
        monthlyIncome: item.monthlyIncome !== undefined ? item.monthlyIncome : null,
    };
}

function serializeWeatherState(item: WeatherState): object {
    return {
        weather: item.weather,
        temperature: item.temperature,
    };
}

function serializeVehicleColour(item: VehicleColour): object {
    return {
        body: item.body,
        trim: item.trim,
        tertiary: item.tertiary,
    };
}

function serializeCoordsXYZ(item: CoordsXYZ): object {
    return {
        x: item.x,
        y: item.y,
        z: item.z,
    };
}

function serializeCoordsXYZD(item: CoordsXYZD): object {
    return {
        x: item.x,
        y: item.y,
        z: item.z,
        direction: item.direction,
    };
}

function serializeRideStation(item: RideStation): object {
    return {
        start: serializeCoordsXYZ(item.start),
        length: item.length,
        entrance: item.entrance != null ? serializeCoordsXYZD(item.entrance) : null,
        exit: item.exit != null ? serializeCoordsXYZD(item.exit) : null,
    };
}

function serializeTrackColour(item: TrackColour): object {
    return {
        main: item.main,
        additional: item.additional,
        supports: item.supports,
    };
}

function serializeInstalledObject(item: InstalledObject): object {
    return {
        path: item.path,
        generation: item.generation,
        type: item.type,
        sourceGames: item.sourceGames,
        identifier: item.identifier,
        legacyIdentifier: item.legacyIdentifier !== undefined ? item.legacyIdentifier : null,
        version: item.version,
        authors: item.authors,
        name: item.name,
    };
}

function serializeSpriteGroup(item: SpriteGroup): object {
    return {
        imageId: item.imageId,
        spriteNumImages: item.spriteNumImages,
    };
}

function serializeSpriteGroups(item: SpriteGroups): object {
    return {
        slopeFlat: item.slopeFlat != null ? serializeSpriteGroup(item.slopeFlat) : null,
        slopes12: item.slopes12 != null ? serializeSpriteGroup(item.slopes12) : null,
        slopes25: item.slopes25 != null ? serializeSpriteGroup(item.slopes25) : null,
        slopes42: item.slopes42 != null ? serializeSpriteGroup(item.slopes42) : null,
        slopes60: item.slopes60 != null ? serializeSpriteGroup(item.slopes60) : null,
        slopes75: item.slopes75 != null ? serializeSpriteGroup(item.slopes75) : null,
        slopes90: item.slopes90 != null ? serializeSpriteGroup(item.slopes90) : null,
        slopesLoop: item.slopesLoop != null ? serializeSpriteGroup(item.slopesLoop) : null,
        slopeInverted: item.slopeInverted != null ? serializeSpriteGroup(item.slopeInverted) : null,
        slopes8: item.slopes8 != null ? serializeSpriteGroup(item.slopes8) : null,
        slopes16: item.slopes16 != null ? serializeSpriteGroup(item.slopes16) : null,
        slopes50: item.slopes50 != null ? serializeSpriteGroup(item.slopes50) : null,
        flatBanked22: item.flatBanked22 != null ? serializeSpriteGroup(item.flatBanked22) : null,
        flatBanked45: item.flatBanked45 != null ? serializeSpriteGroup(item.flatBanked45) : null,
        flatBanked67: item.flatBanked67 != null ? serializeSpriteGroup(item.flatBanked67) : null,
        flatBanked90: item.flatBanked90 != null ? serializeSpriteGroup(item.flatBanked90) : null,
        inlineTwists: item.inlineTwists != null ? serializeSpriteGroup(item.inlineTwists) : null,
        slopes12Banked22: item.slopes12Banked22 != null ? serializeSpriteGroup(item.slopes12Banked22) : null,
        slopes8Banked22: item.slopes8Banked22 != null ? serializeSpriteGroup(item.slopes8Banked22) : null,
        slopes25Banked22: item.slopes25Banked22 != null ? serializeSpriteGroup(item.slopes25Banked22) : null,
        slopes8Banked45: item.slopes8Banked45 != null ? serializeSpriteGroup(item.slopes8Banked45) : null,
        slopes16Banked22: item.slopes16Banked22 != null ? serializeSpriteGroup(item.slopes16Banked22) : null,
        slopes16Banked45: item.slopes16Banked45 != null ? serializeSpriteGroup(item.slopes16Banked45) : null,
        slopes25Banked45: item.slopes25Banked45 != null ? serializeSpriteGroup(item.slopes25Banked45) : null,
        slopes12Banked45: item.slopes12Banked45 != null ? serializeSpriteGroup(item.slopes12Banked45) : null,
        slopes25Banked67: item.slopes25Banked67 != null ? serializeSpriteGroup(item.slopes25Banked67) : null,
        slopes25InlineTwists: item.slopes25InlineTwists != null ? serializeSpriteGroup(item.slopes25InlineTwists) : null,
        slopes42Banked22: item.slopes42Banked22 != null ? serializeSpriteGroup(item.slopes42Banked22) : null,
        slopes42Banked45: item.slopes42Banked45 != null ? serializeSpriteGroup(item.slopes42Banked45) : null,
        slopes42Banked90: item.slopes42Banked90 != null ? serializeSpriteGroup(item.slopes42Banked90) : null,
        slopes60Banked22: item.slopes60Banked22 != null ? serializeSpriteGroup(item.slopes60Banked22) : null,
        corkscrews: item.corkscrews != null ? serializeSpriteGroup(item.corkscrews) : null,
        restraintAnimation: item.restraintAnimation != null ? serializeSpriteGroup(item.restraintAnimation) : null,
        curvedLiftHillUp: item.curvedLiftHillUp != null ? serializeSpriteGroup(item.curvedLiftHillUp) : null,
        curvedLiftHillDown: item.curvedLiftHillDown != null ? serializeSpriteGroup(item.curvedLiftHillDown) : null,
    };
}

function serializeRideObjectVehicle(item: RideObjectVehicle): object {
    return {
        rotationFrameMask: item.rotationFrameMask,
        spacing: item.spacing,
        carMass: item.carMass,
        tabHeight: item.tabHeight,
        numSeats: item.numSeats,
        spriteFlags: item.spriteFlags,
        spriteWidth: item.spriteWidth,
        spriteHeightNegative: item.spriteHeightNegative,
        spriteHeightPositive: item.spriteHeightPositive,
        animation: item.animation,
        flags: item.flags,
        baseNumFrames: item.baseNumFrames,
        baseImageId: item.baseImageId,
        spriteGroups: serializeSpriteGroups(item.spriteGroups),
        noVehicleImages: item.noVehicleImages,
        noSeatingRows: item.noSeatingRows,
        spinningInertia: item.spinningInertia,
        spinningFriction: item.spinningFriction,
        frictionSoundId: item.frictionSoundId,
        logFlumeReverserVehicleType: item.logFlumeReverserVehicleType,
        soundRange: item.soundRange,
        doubleSoundFrequency: item.doubleSoundFrequency,
        poweredAcceleration: item.poweredAcceleration,
        poweredMaxSpeed: item.poweredMaxSpeed,
        carVisual: item.carVisual,
        effectVisual: item.effectVisual,
        drawOrder: item.drawOrder,
        numVerticalFramesOverride: item.numVerticalFramesOverride,
    };
}

function serializeRideObject(item: RideObject): object {
    var vehicles: object[] = [];
    for (var i_vehicles = 0; i_vehicles < item.vehicles.length; i_vehicles++) {
        vehicles.push(serializeRideObjectVehicle(item.vehicles[i_vehicles]));
    }
    return {
        installedObject: serializeInstalledObject(item.installedObject),
        type: item.type,
        index: item.index,
        identifier: item.identifier,
        legacyIdentifier: item.legacyIdentifier,
        name: item.name,
        baseImageId: item.baseImageId,
        numImages: item.numImages,
        description: item.description,
        capacity: item.capacity,
        flags: item.flags,
        rideType: item.rideType,
        minCarsInTrain: item.minCarsInTrain,
        maxCarsInTrain: item.maxCarsInTrain,
        carsPerFlatRide: item.carsPerFlatRide,
        zeroCars: item.zeroCars,
        tabVehicle: item.tabVehicle,
        defaultVehicle: item.defaultVehicle,
        frontVehicle: item.frontVehicle,
        secondVehicle: item.secondVehicle,
        rearVehicle: item.rearVehicle,
        thirdVehicle: item.thirdVehicle,
        vehicles: vehicles,
        excitementMultiplier: item.excitementMultiplier,
        intensityMultiplier: item.intensityMultiplier,
        nauseaMultiplier: item.nauseaMultiplier,
        maxHeight: item.maxHeight,
        shopItem: item.shopItem,
        shopItemSecondary: item.shopItemSecondary,
    };
}

function serializeRide(item: Ride): object {
    var vehicleColours: object[] = [];
    for (var i_vehicleColours = 0; i_vehicleColours < item.vehicleColours.length; i_vehicleColours++) {
        vehicleColours.push(serializeVehicleColour(item.vehicleColours[i_vehicleColours]));
    }
    var colourSchemes: object[] = [];
    for (var i_colourSchemes = 0; i_colourSchemes < item.colourSchemes.length; i_colourSchemes++) {
        colourSchemes.push(serializeTrackColour(item.colourSchemes[i_colourSchemes]));
    }
    var stations: object[] = [];
    for (var i_stations = 0; i_stations < item.stations.length; i_stations++) {
        stations.push(serializeRideStation(item.stations[i_stations]));
    }
    return {
        object: serializeRideObject(item.object),
        id: item.id,
        type: item.type,
        classification: item.classification,
        name: item.name,
        status: item.status,
        flags: item.flags,
        lifecycleFlags: item.lifecycleFlags,
        mode: item.mode,
        departFlags: item.departFlags,
        minimumWaitingTime: item.minimumWaitingTime,
        maximumWaitingTime: item.maximumWaitingTime,
        vehicles: item.vehicles,
        vehicleColours: vehicleColours,
        colourSchemes: colourSchemes,
        stationStyle: item.stationStyle,
        music: item.music,
        stations: stations,
        price: item.price,
        excitement: item.excitement,
        intensity: item.intensity,
        nausea: item.nausea,
        totalCustomers: item.totalCustomers,
        buildDate: item.buildDate,
        age: item.age,
        runningCost: item.runningCost,
        totalProfit: item.totalProfit,
        inspectionInterval: item.inspectionInterval,
        value: item.value,
        downtime: item.downtime,
        liftHillSpeed: item.liftHillSpeed,
        maxLiftHillSpeed: item.maxLiftHillSpeed,
        minLiftHillSpeed: item.minLiftHillSpeed,
        satisfaction: item.satisfaction,
        maxSpeed: item.maxSpeed,
        averageSpeed: item.averageSpeed,
        rideTime: item.rideTime,
        rideLength: item.rideLength,
        maxPositiveVerticalGs: item.maxPositiveVerticalGs,
        maxNegativeVerticalGs: item.maxNegativeVerticalGs,
        maxLateralGs: item.maxLateralGs,
        totalAirTime: item.totalAirTime,
        numDrops: item.numDrops,
        numLiftHills: item.numLiftHills,
        highestDropHeight: item.highestDropHeight,
        breakdown: item.breakdown,
    };
}

function serializeCoordsXY(item: CoordsXY): object {
    return {
        x: item.x,
        y: item.y,
    };
}

function serializePatrolArea(item: PatrolArea): object {
    var tiles: object[] = [];
    for (var i_tiles = 0; i_tiles < item.tiles.length; i_tiles++) {
        tiles.push(serializeCoordsXY(item.tiles[i_tiles]));
    }
    return {
        tiles: tiles,
    };
}

function serializeGuestItem(item: GuestItem): object {
    return {
        type: item.type,
    };
}

function serializeThought(item: Thought): object {
    return {
        type: item.type,
        item: item.item,
        freshness: item.freshness,
        freshTimeout: item.freshTimeout,
    };
}

function serializeGuest(item: Guest): object {
    var flags: any = {};
    flags["leavingPark"] = item.getFlag("leavingPark");
    flags["slowWalk"] = item.getFlag("slowWalk");
    flags["tracking"] = item.getFlag("tracking");
    flags["waving"] = item.getFlag("waving");
    flags["hasPaidForParkEntry"] = item.getFlag("hasPaidForParkEntry");
    flags["photo"] = item.getFlag("photo");
    flags["painting"] = item.getFlag("painting");
    flags["wow"] = item.getFlag("wow");
    flags["litter"] = item.getFlag("litter");
    flags["lost"] = item.getFlag("lost");
    flags["hunger"] = item.getFlag("hunger");
    flags["toilet"] = item.getFlag("toilet");
    flags["crowded"] = item.getFlag("crowded");
    flags["happiness"] = item.getFlag("happiness");
    flags["nausea"] = item.getFlag("nausea");
    flags["purple"] = item.getFlag("purple");
    flags["pizza"] = item.getFlag("pizza");
    flags["explode"] = item.getFlag("explode");
    flags["rideShouldBeMarkedAsFavourite"] = item.getFlag("rideShouldBeMarkedAsFavourite");
    flags["parkEntranceChosen"] = item.getFlag("parkEntranceChosen");
    flags["contagious"] = item.getFlag("contagious");
    flags["joy"] = item.getFlag("joy");
    flags["angry"] = item.getFlag("angry");
    flags["iceCream"] = item.getFlag("iceCream");
    flags["hereWeAre"] = item.getFlag("hereWeAre");
    flags["positionFrozen"] = item.getFlag("positionFrozen");
    flags["animationFrozen"] = item.getFlag("animationFrozen");
    var thoughts: object[] = [];
    for (var i_thoughts = 0; i_thoughts < item.thoughts.length; i_thoughts++) {
        thoughts.push(serializeThought(item.thoughts[i_thoughts]));
    }
    var items: object[] = [];
    for (var i_items = 0; i_items < item.items.length; i_items++) {
        items.push(serializeGuestItem(item.items[i_items]));
    }
    return {
        id: item.id !== undefined ? item.id : null,
        type: item.type,
        x: item.x,
        y: item.y,
        z: item.z,
        flags: flags,
        peepType: item.peepType,
        name: item.name,
        destination: serializeCoordsXY(item.destination),
        direction: item.direction,
        energy: item.energy,
        energyTarget: item.energyTarget,
        tshirtColour: item.tshirtColour,
        trousersColour: item.trousersColour,
        balloonColour: item.balloonColour,
        hatColour: item.hatColour,
        umbrellaColour: item.umbrellaColour,
        happiness: item.happiness,
        happinessTarget: item.happinessTarget,
        nausea: item.nausea,
        nauseaTarget: item.nauseaTarget,
        hunger: item.hunger,
        thirst: item.thirst,
        toilet: item.toilet,
        mass: item.mass,
        minIntensity: item.minIntensity,
        maxIntensity: item.maxIntensity,
        nauseaTolerance: item.nauseaTolerance,
        cash: item.cash,
        isInPark: item.isInPark,
        isLost: item.isLost,
        lostCountdown: item.lostCountdown,
        thoughts: thoughts,
        items: items,
        availableAnimations: item.availableAnimations,
        animation: item.animation,
        animationOffset: item.animationOffset,
        animationLength: item.animationLength,
        favouriteRide: item.favouriteRide !== undefined ? item.favouriteRide : null,
    };
}

// ── Namespace property helpers ───────────────────────────────────────────────

function getParkFlags(): object {
    var flags: any = {};
    flags["difficultGuestGeneration"] = park.getFlag("difficultGuestGeneration");
    flags["difficultParkRating"] = park.getFlag("difficultParkRating");
    flags["forbidHighConstruction"] = park.getFlag("forbidHighConstruction");
    flags["forbidLandscapeChanges"] = park.getFlag("forbidLandscapeChanges");
    flags["forbidMarketingCampaigns"] = park.getFlag("forbidMarketingCampaigns");
    flags["forbidTreeRemoval"] = park.getFlag("forbidTreeRemoval");
    flags["freeParkEntry"] = park.getFlag("freeParkEntry");
    flags["noMoney"] = park.getFlag("noMoney");
    flags["open"] = park.getFlag("open");
    flags["preferLessIntenseRides"] = park.getFlag("preferLessIntenseRides");
    flags["preferMoreIntenseRides"] = park.getFlag("preferMoreIntenseRides");
    flags["scenarioCompleteNameInput"] = park.getFlag("scenarioCompleteNameInput");
    flags["unlockAllPrices"] = park.getFlag("unlockAllPrices");
    return flags;
}

function getParkResearch(): object {
    return serializeResearch(park.research);
}

function getParkMessages(): object[] {
    var result: object[] = [];
    for (var i = 0; i < park.messages.length; i++) {
        result.push(serializeParkMessage(park.messages[i]));
    }
    return result;
}

function getParkAwards(): object[] {
    var result: object[] = [];
    for (var i = 0; i < park.awards.length; i++) {
        result.push(serializeAward(park.awards[i]));
    }
    return result;
}

function getScenarioObjective(): object {
    return serializeScenarioObjective(scenario.objective);
}

function getClimateCurrent(): object {
    return serializeWeatherState(climate.current);
}

function getClimateFuture(): object {
    return serializeWeatherState(climate.future);
}

// ── Namespace getters ────────────────────────────────────────────────────────

function getPark(): object {
    return {
        flags: getParkFlags(),
        cash: park.cash,
        rating: park.rating,
        bankLoan: park.bankLoan,
        maxBankLoan: park.maxBankLoan,
        entranceFee: park.entranceFee,
        guests: park.guests,
        suggestedGuestMaximum: park.suggestedGuestMaximum,
        guestGenerationProbability: park.guestGenerationProbability,
        guestInitialCash: park.guestInitialCash,
        guestInitialHappiness: park.guestInitialHappiness,
        guestInitialHunger: park.guestInitialHunger,
        guestInitialThirst: park.guestInitialThirst,
        value: park.value,
        companyValue: park.companyValue,
        totalRideValueForMoney: park.totalRideValueForMoney,
        totalAdmissions: park.totalAdmissions,
        totalIncomeFromAdmissions: park.totalIncomeFromAdmissions,
        landPrice: park.landPrice,
        constructionRightsPrice: park.constructionRightsPrice,
        casualtyPenalty: park.casualtyPenalty,
        parkSize: park.parkSize,
        name: park.name,
        research: getParkResearch(),
        messages: getParkMessages(),
        awards: getParkAwards(),
    };
}

function getCheats(): object {
    return {
        allowArbitraryRideTypeChanges: cheats.allowArbitraryRideTypeChanges,
        allowSpecialColourSchemes: cheats.allowSpecialColourSchemes,
        allowTrackPlaceInvalidHeights: cheats.allowTrackPlaceInvalidHeights,
        buildInPauseMode: cheats.buildInPauseMode,
        disableAllBreakdowns: cheats.disableAllBreakdowns,
        disableBrakesFailure: cheats.disableBrakesFailure,
        disableClearanceChecks: cheats.disableClearanceChecks,
        disableLittering: cheats.disableLittering,
        disablePlantAging: cheats.disablePlantAging,
        disableRideValueAging: cheats.disableRideValueAging,
        disableSupportLimits: cheats.disableSupportLimits,
        disableTrainLengthLimit: cheats.disableTrainLengthLimit,
        disableVandalism: cheats.disableVandalism,
        enableAllDrawableTrackPieces: cheats.enableAllDrawableTrackPieces,
        enableChainLiftOnAllTrack: cheats.enableChainLiftOnAllTrack,
        fastLiftHill: cheats.fastLiftHill,
        forcedParkRating: cheats.forcedParkRating,
        freezeWeather: cheats.freezeWeather,
        ignoreResearchStatus: cheats.ignoreResearchStatus,
        ignoreRideIntensity: cheats.ignoreRideIntensity,
        ignoreRidePrice: cheats.ignoreRidePrice,
        neverendingMarketing: cheats.neverendingMarketing,
        makeAllDestructible: cheats.makeAllDestructible,
        sandboxMode: cheats.sandboxMode,
        showAllOperatingModes: cheats.showAllOperatingModes,
        showVehiclesFromOtherTrackTypes: cheats.showVehiclesFromOtherTrackTypes,
        allowRegularPathAsQueue: cheats.allowRegularPathAsQueue,
    };
}

function getDate(): object {
    return {
        ticksElapsed: date.ticksElapsed,
        monthsElapsed: date.monthsElapsed,
        yearsElapsed: date.yearsElapsed,
        monthProgress: date.monthProgress,
        day: date.day,
        month: date.month,
        year: date.year,
    };
}

function getScenario(): object {
    return {
        name: scenario.name,
        details: scenario.details,
        completedBy: scenario.completedBy,
        filename: scenario.filename,
        objective: getScenarioObjective(),
        parkRatingWarningDays: scenario.parkRatingWarningDays,
        completedCompanyValue: scenario.completedCompanyValue !== undefined ? scenario.completedCompanyValue : null,
        status: scenario.status,
        companyValueRecord: scenario.companyValueRecord,
    };
}

function getClimate(): object {
    return {
        type: climate.type,
        current: getClimateCurrent(),
        future: getClimateFuture(),
    };
}

// ── Entity collection getters ────────────────────────────────────────────────

function getRides(): object[] {
    var items = map.rides;
    var result: object[] = [];
    for (var i = 0; i < items.length; i++) {
        result.push(serializeRide(items[i] as Ride));
    }
    return result;
}

function getStaff(): object[] {
    var items = map.getAllEntities("staff");
    var result: object[] = [];
    for (var i = 0; i < items.length; i++) {
        result.push(serializeStaff(items[i] as Staff));
    }
    return result;
}

function getGuests(): object[] {
    var items = map.getAllEntities("guest");
    var result: object[] = [];
    for (var i = 0; i < items.length; i++) {
        result.push(serializeGuest(items[i] as Guest));
    }
    return result;
}

// ── Router ────────────────────────────────────────────────────────────────────

/**
 * Handle state query endpoints.
 *
 * Returns true if the endpoint was handled, false otherwise.
 * Endpoints: one per namespace root + one per property sub-path,
 * plus one per entity collection.
 */
export function handleQuery(endpoint: string, params: any, reply: (response: object) => void): boolean {
    switch (endpoint) {
        case "park":
            reply({ success: true, payload: getPark() });
            return true;
        case "park.flags":
            reply({ success: true, payload: getParkFlags() });
            return true;
        case "park.cash":
            reply({ success: true, payload: park.cash });
            return true;
        case "park.rating":
            reply({ success: true, payload: park.rating });
            return true;
        case "park.bankLoan":
            reply({ success: true, payload: park.bankLoan });
            return true;
        case "park.maxBankLoan":
            reply({ success: true, payload: park.maxBankLoan });
            return true;
        case "park.entranceFee":
            reply({ success: true, payload: park.entranceFee });
            return true;
        case "park.guests":
            reply({ success: true, payload: park.guests });
            return true;
        case "park.suggestedGuestMaximum":
            reply({ success: true, payload: park.suggestedGuestMaximum });
            return true;
        case "park.guestGenerationProbability":
            reply({ success: true, payload: park.guestGenerationProbability });
            return true;
        case "park.guestInitialCash":
            reply({ success: true, payload: park.guestInitialCash });
            return true;
        case "park.guestInitialHappiness":
            reply({ success: true, payload: park.guestInitialHappiness });
            return true;
        case "park.guestInitialHunger":
            reply({ success: true, payload: park.guestInitialHunger });
            return true;
        case "park.guestInitialThirst":
            reply({ success: true, payload: park.guestInitialThirst });
            return true;
        case "park.value":
            reply({ success: true, payload: park.value });
            return true;
        case "park.companyValue":
            reply({ success: true, payload: park.companyValue });
            return true;
        case "park.totalRideValueForMoney":
            reply({ success: true, payload: park.totalRideValueForMoney });
            return true;
        case "park.totalAdmissions":
            reply({ success: true, payload: park.totalAdmissions });
            return true;
        case "park.totalIncomeFromAdmissions":
            reply({ success: true, payload: park.totalIncomeFromAdmissions });
            return true;
        case "park.landPrice":
            reply({ success: true, payload: park.landPrice });
            return true;
        case "park.constructionRightsPrice":
            reply({ success: true, payload: park.constructionRightsPrice });
            return true;
        case "park.casualtyPenalty":
            reply({ success: true, payload: park.casualtyPenalty });
            return true;
        case "park.parkSize":
            reply({ success: true, payload: park.parkSize });
            return true;
        case "park.name":
            reply({ success: true, payload: park.name });
            return true;
        case "park.research":
            reply({ success: true, payload: getParkResearch() });
            return true;
        case "park.messages":
            reply({ success: true, payload: getParkMessages() });
            return true;
        case "park.awards":
            reply({ success: true, payload: getParkAwards() });
            return true;
        case "cheats":
            reply({ success: true, payload: getCheats() });
            return true;
        case "cheats.allowArbitraryRideTypeChanges":
            reply({ success: true, payload: cheats.allowArbitraryRideTypeChanges });
            return true;
        case "cheats.allowSpecialColourSchemes":
            reply({ success: true, payload: cheats.allowSpecialColourSchemes });
            return true;
        case "cheats.allowTrackPlaceInvalidHeights":
            reply({ success: true, payload: cheats.allowTrackPlaceInvalidHeights });
            return true;
        case "cheats.buildInPauseMode":
            reply({ success: true, payload: cheats.buildInPauseMode });
            return true;
        case "cheats.disableAllBreakdowns":
            reply({ success: true, payload: cheats.disableAllBreakdowns });
            return true;
        case "cheats.disableBrakesFailure":
            reply({ success: true, payload: cheats.disableBrakesFailure });
            return true;
        case "cheats.disableClearanceChecks":
            reply({ success: true, payload: cheats.disableClearanceChecks });
            return true;
        case "cheats.disableLittering":
            reply({ success: true, payload: cheats.disableLittering });
            return true;
        case "cheats.disablePlantAging":
            reply({ success: true, payload: cheats.disablePlantAging });
            return true;
        case "cheats.disableRideValueAging":
            reply({ success: true, payload: cheats.disableRideValueAging });
            return true;
        case "cheats.disableSupportLimits":
            reply({ success: true, payload: cheats.disableSupportLimits });
            return true;
        case "cheats.disableTrainLengthLimit":
            reply({ success: true, payload: cheats.disableTrainLengthLimit });
            return true;
        case "cheats.disableVandalism":
            reply({ success: true, payload: cheats.disableVandalism });
            return true;
        case "cheats.enableAllDrawableTrackPieces":
            reply({ success: true, payload: cheats.enableAllDrawableTrackPieces });
            return true;
        case "cheats.enableChainLiftOnAllTrack":
            reply({ success: true, payload: cheats.enableChainLiftOnAllTrack });
            return true;
        case "cheats.fastLiftHill":
            reply({ success: true, payload: cheats.fastLiftHill });
            return true;
        case "cheats.forcedParkRating":
            reply({ success: true, payload: cheats.forcedParkRating });
            return true;
        case "cheats.freezeWeather":
            reply({ success: true, payload: cheats.freezeWeather });
            return true;
        case "cheats.ignoreResearchStatus":
            reply({ success: true, payload: cheats.ignoreResearchStatus });
            return true;
        case "cheats.ignoreRideIntensity":
            reply({ success: true, payload: cheats.ignoreRideIntensity });
            return true;
        case "cheats.ignoreRidePrice":
            reply({ success: true, payload: cheats.ignoreRidePrice });
            return true;
        case "cheats.neverendingMarketing":
            reply({ success: true, payload: cheats.neverendingMarketing });
            return true;
        case "cheats.makeAllDestructible":
            reply({ success: true, payload: cheats.makeAllDestructible });
            return true;
        case "cheats.sandboxMode":
            reply({ success: true, payload: cheats.sandboxMode });
            return true;
        case "cheats.showAllOperatingModes":
            reply({ success: true, payload: cheats.showAllOperatingModes });
            return true;
        case "cheats.showVehiclesFromOtherTrackTypes":
            reply({ success: true, payload: cheats.showVehiclesFromOtherTrackTypes });
            return true;
        case "cheats.allowRegularPathAsQueue":
            reply({ success: true, payload: cheats.allowRegularPathAsQueue });
            return true;
        case "date":
            reply({ success: true, payload: getDate() });
            return true;
        case "date.ticksElapsed":
            reply({ success: true, payload: date.ticksElapsed });
            return true;
        case "date.monthsElapsed":
            reply({ success: true, payload: date.monthsElapsed });
            return true;
        case "date.yearsElapsed":
            reply({ success: true, payload: date.yearsElapsed });
            return true;
        case "date.monthProgress":
            reply({ success: true, payload: date.monthProgress });
            return true;
        case "date.day":
            reply({ success: true, payload: date.day });
            return true;
        case "date.month":
            reply({ success: true, payload: date.month });
            return true;
        case "date.year":
            reply({ success: true, payload: date.year });
            return true;
        case "scenario":
            reply({ success: true, payload: getScenario() });
            return true;
        case "scenario.name":
            reply({ success: true, payload: scenario.name });
            return true;
        case "scenario.details":
            reply({ success: true, payload: scenario.details });
            return true;
        case "scenario.completedBy":
            reply({ success: true, payload: scenario.completedBy });
            return true;
        case "scenario.filename":
            reply({ success: true, payload: scenario.filename });
            return true;
        case "scenario.objective":
            reply({ success: true, payload: getScenarioObjective() });
            return true;
        case "scenario.parkRatingWarningDays":
            reply({ success: true, payload: scenario.parkRatingWarningDays });
            return true;
        case "scenario.completedCompanyValue":
            reply({ success: true, payload: scenario.completedCompanyValue !== undefined ? scenario.completedCompanyValue : null });
            return true;
        case "scenario.status":
            reply({ success: true, payload: scenario.status });
            return true;
        case "scenario.companyValueRecord":
            reply({ success: true, payload: scenario.companyValueRecord });
            return true;
        case "climate":
            reply({ success: true, payload: getClimate() });
            return true;
        case "climate.type":
            reply({ success: true, payload: climate.type });
            return true;
        case "climate.current":
            reply({ success: true, payload: getClimateCurrent() });
            return true;
        case "climate.future":
            reply({ success: true, payload: getClimateFuture() });
            return true;
        case "rides":
            reply({ success: true, payload: getRides() });
            return true;
        case "staff":
            reply({ success: true, payload: getStaff() });
            return true;
        case "guests":
            reply({ success: true, payload: getGuests() });
            return true;
        default:
            return false;
    }
}
