/// <reference path="../lib/openrct2.d.ts" />

// Auto-generated by openrct2-codegen 0.2.0
// OpenRCT2 v0.4.32 (API v110)
// Generated: 2026-03-14T22:51:35.846982+00:00
//
// DO NOT EDIT -- regenerate with: openrct2-codegen generate

// ── Interface serializers (union variants) ───────────────────────────────────

function serializeRideResearchItem(item: RideResearchItem): object {
    return {
        type: item.type,
        category: item.category,
        rideType: item.rideType,
        object: item.object,
    };
}

function serializeSceneryResearchItem(item: SceneryResearchItem): object {
    return {
        category: item.category,
        type: item.type,
        object: item.object,
    };
}

// ── Union serializers ────────────────────────────────────────────────────────

function serializeResearchItem(item: ResearchItem): object {
    if (item.type === "ride") {
        return serializeRideResearchItem(item as RideResearchItem);
    } else {
        return serializeSceneryResearchItem(item as SceneryResearchItem);
    }
}

// ── Interface serializers ────────────────────────────────────────────────────

function serializeResearch(item: Research): object {
    var inventedItems: object[] = [];
    for (var i_inventedItems = 0; i_inventedItems < item.inventedItems.length; i_inventedItems++) {
        inventedItems.push(serializeResearchItem(item.inventedItems[i_inventedItems]));
    }
    var uninventedItems: object[] = [];
    for (var i_uninventedItems = 0; i_uninventedItems < item.uninventedItems.length; i_uninventedItems++) {
        uninventedItems.push(serializeResearchItem(item.uninventedItems[i_uninventedItems]));
    }
    return {
        inventedItems: inventedItems,
        uninventedItems: uninventedItems,
        lastResearchedItem: item.lastResearchedItem !== null ? serializeResearchItem(item.lastResearchedItem as ResearchItem) : null,
        expectedItem: item.expectedItem !== null ? serializeResearchItem(item.expectedItem as ResearchItem) : null,
        funding: item.funding,
        priorities: item.priorities,
        stage: item.stage,
        progress: item.progress,
        expectedMonth: item.expectedMonth !== undefined ? item.expectedMonth : null,
        expectedDay: item.expectedDay !== undefined ? item.expectedDay : null,
    };
}

function serializeParkMessage(item: ParkMessage): object {
    return {
        isArchived: item.isArchived,
        month: item.month,
        day: item.day,
        tickCount: item.tickCount,
        type: item.type,
        text: item.text,
        subject: item.subject !== undefined ? item.subject : null,
    };
}

function serializeAward(item: Award): object {
    return {
        type: item.type,
        text: item.text,
        monthsRemaining: item.monthsRemaining,
        imageId: item.imageId,
        positive: item.positive,
    };
}

function serializeScenarioObjective(item: ScenarioObjective): object {
    return {
        type: item.type,
        guests: item.guests,
        year: item.year,
        length: item.length,
        excitement: item.excitement,
        parkValue: item.parkValue,
        monthlyIncome: item.monthlyIncome,
    };
}

function serializeWeatherState(item: WeatherState): object {
    return {
        weather: item.weather,
        temperature: item.temperature,
    };
}

// ── Namespace property helpers ───────────────────────────────────────────────

function getParkFlags(): object {
    var flags: any = {};
    flags["difficultGuestGeneration"] = park.getFlag("difficultGuestGeneration");
    flags["difficultParkRating"] = park.getFlag("difficultParkRating");
    flags["forbidHighConstruction"] = park.getFlag("forbidHighConstruction");
    flags["forbidLandscapeChanges"] = park.getFlag("forbidLandscapeChanges");
    flags["forbidMarketingCampaigns"] = park.getFlag("forbidMarketingCampaigns");
    flags["forbidTreeRemoval"] = park.getFlag("forbidTreeRemoval");
    flags["freeParkEntry"] = park.getFlag("freeParkEntry");
    flags["noMoney"] = park.getFlag("noMoney");
    flags["open"] = park.getFlag("open");
    flags["preferLessIntenseRides"] = park.getFlag("preferLessIntenseRides");
    flags["preferMoreIntenseRides"] = park.getFlag("preferMoreIntenseRides");
    flags["scenarioCompleteNameInput"] = park.getFlag("scenarioCompleteNameInput");
    flags["unlockAllPrices"] = park.getFlag("unlockAllPrices");
    return flags;
}

function getParkResearch(): object {
    return serializeResearch(park.research);
}

function getParkMessages(): object[] {
    var result: object[] = [];
    for (var i = 0; i < park.messages.length; i++) {
        result.push(serializeParkMessage(park.messages[i]));
    }
    return result;
}

function getParkAwards(): object[] {
    var result: object[] = [];
    for (var i = 0; i < park.awards.length; i++) {
        result.push(serializeAward(park.awards[i]));
    }
    return result;
}

function getScenarioObjective(): object {
    return serializeScenarioObjective(scenario.objective);
}

function getClimateCurrent(): object {
    return serializeWeatherState(climate.current);
}

function getClimateFuture(): object {
    return serializeWeatherState(climate.future);
}

// ── Namespace getters ────────────────────────────────────────────────────────

function getPark(): object {
    return {
        flags: getParkFlags(),
        cash: park.cash,
        rating: park.rating,
        bankLoan: park.bankLoan,
        maxBankLoan: park.maxBankLoan,
        entranceFee: park.entranceFee,
        guests: park.guests,
        suggestedGuestMaximum: park.suggestedGuestMaximum,
        guestGenerationProbability: park.guestGenerationProbability,
        guestInitialCash: park.guestInitialCash,
        guestInitialHappiness: park.guestInitialHappiness,
        guestInitialHunger: park.guestInitialHunger,
        guestInitialThirst: park.guestInitialThirst,
        value: park.value,
        companyValue: park.companyValue,
        totalRideValueForMoney: park.totalRideValueForMoney,
        totalAdmissions: park.totalAdmissions,
        totalIncomeFromAdmissions: park.totalIncomeFromAdmissions,
        landPrice: park.landPrice,
        constructionRightsPrice: park.constructionRightsPrice,
        casualtyPenalty: park.casualtyPenalty,
        parkSize: park.parkSize,
        name: park.name,
        research: getParkResearch(),
        messages: getParkMessages(),
        awards: getParkAwards(),
    };
}

function getCheats(): object {
    return {
        allowArbitraryRideTypeChanges: cheats.allowArbitraryRideTypeChanges,
        allowSpecialColourSchemes: cheats.allowSpecialColourSchemes,
        allowTrackPlaceInvalidHeights: cheats.allowTrackPlaceInvalidHeights,
        buildInPauseMode: cheats.buildInPauseMode,
        disableAllBreakdowns: cheats.disableAllBreakdowns,
        disableBrakesFailure: cheats.disableBrakesFailure,
        disableClearanceChecks: cheats.disableClearanceChecks,
        disableLittering: cheats.disableLittering,
        disablePlantAging: cheats.disablePlantAging,
        disableRideValueAging: cheats.disableRideValueAging,
        disableSupportLimits: cheats.disableSupportLimits,
        disableTrainLengthLimit: cheats.disableTrainLengthLimit,
        disableVandalism: cheats.disableVandalism,
        enableAllDrawableTrackPieces: cheats.enableAllDrawableTrackPieces,
        enableChainLiftOnAllTrack: cheats.enableChainLiftOnAllTrack,
        fastLiftHill: cheats.fastLiftHill,
        forcedParkRating: cheats.forcedParkRating,
        freezeWeather: cheats.freezeWeather,
        ignoreResearchStatus: cheats.ignoreResearchStatus,
        ignoreRideIntensity: cheats.ignoreRideIntensity,
        ignoreRidePrice: cheats.ignoreRidePrice,
        neverendingMarketing: cheats.neverendingMarketing,
        makeAllDestructible: cheats.makeAllDestructible,
        sandboxMode: cheats.sandboxMode,
        showAllOperatingModes: cheats.showAllOperatingModes,
        showVehiclesFromOtherTrackTypes: cheats.showVehiclesFromOtherTrackTypes,
        allowRegularPathAsQueue: cheats.allowRegularPathAsQueue,
    };
}

function getDate(): object {
    return {
        ticksElapsed: date.ticksElapsed,
        monthsElapsed: date.monthsElapsed,
        yearsElapsed: date.yearsElapsed,
        monthProgress: date.monthProgress,
        day: date.day,
        month: date.month,
        year: date.year,
    };
}

function getScenario(): object {
    return {
        name: scenario.name,
        details: scenario.details,
        completedBy: scenario.completedBy,
        filename: scenario.filename,
        objective: getScenarioObjective(),
        parkRatingWarningDays: scenario.parkRatingWarningDays,
        completedCompanyValue: scenario.completedCompanyValue !== undefined ? scenario.completedCompanyValue : null,
        status: scenario.status,
        companyValueRecord: scenario.companyValueRecord,
    };
}

function getClimate(): object {
    return {
        type: climate.type,
        current: getClimateCurrent(),
        future: getClimateFuture(),
    };
}

// ── Router ────────────────────────────────────────────────────────────────────

/**
 * Handle state query endpoints.
 *
 * Returns true if the endpoint was handled, false otherwise.
 * Endpoints: one per namespace root + one per property sub-path.
 */
export function handleQuery(endpoint: string, params: any, reply: (response: object) => void): boolean {
    switch (endpoint) {
        case "park":
            reply({ success: true, payload: getPark() });
            return true;
        case "park.flags":
            reply({ success: true, payload: getParkFlags() });
            return true;
        case "park.cash":
            reply({ success: true, payload: park.cash });
            return true;
        case "park.rating":
            reply({ success: true, payload: park.rating });
            return true;
        case "park.bankLoan":
            reply({ success: true, payload: park.bankLoan });
            return true;
        case "park.maxBankLoan":
            reply({ success: true, payload: park.maxBankLoan });
            return true;
        case "park.entranceFee":
            reply({ success: true, payload: park.entranceFee });
            return true;
        case "park.guests":
            reply({ success: true, payload: park.guests });
            return true;
        case "park.suggestedGuestMaximum":
            reply({ success: true, payload: park.suggestedGuestMaximum });
            return true;
        case "park.guestGenerationProbability":
            reply({ success: true, payload: park.guestGenerationProbability });
            return true;
        case "park.guestInitialCash":
            reply({ success: true, payload: park.guestInitialCash });
            return true;
        case "park.guestInitialHappiness":
            reply({ success: true, payload: park.guestInitialHappiness });
            return true;
        case "park.guestInitialHunger":
            reply({ success: true, payload: park.guestInitialHunger });
            return true;
        case "park.guestInitialThirst":
            reply({ success: true, payload: park.guestInitialThirst });
            return true;
        case "park.value":
            reply({ success: true, payload: park.value });
            return true;
        case "park.companyValue":
            reply({ success: true, payload: park.companyValue });
            return true;
        case "park.totalRideValueForMoney":
            reply({ success: true, payload: park.totalRideValueForMoney });
            return true;
        case "park.totalAdmissions":
            reply({ success: true, payload: park.totalAdmissions });
            return true;
        case "park.totalIncomeFromAdmissions":
            reply({ success: true, payload: park.totalIncomeFromAdmissions });
            return true;
        case "park.landPrice":
            reply({ success: true, payload: park.landPrice });
            return true;
        case "park.constructionRightsPrice":
            reply({ success: true, payload: park.constructionRightsPrice });
            return true;
        case "park.casualtyPenalty":
            reply({ success: true, payload: park.casualtyPenalty });
            return true;
        case "park.parkSize":
            reply({ success: true, payload: park.parkSize });
            return true;
        case "park.name":
            reply({ success: true, payload: park.name });
            return true;
        case "park.research":
            reply({ success: true, payload: getParkResearch() });
            return true;
        case "park.messages":
            reply({ success: true, payload: getParkMessages() });
            return true;
        case "park.awards":
            reply({ success: true, payload: getParkAwards() });
            return true;
        case "cheats":
            reply({ success: true, payload: getCheats() });
            return true;
        case "cheats.allowArbitraryRideTypeChanges":
            reply({ success: true, payload: cheats.allowArbitraryRideTypeChanges });
            return true;
        case "cheats.allowSpecialColourSchemes":
            reply({ success: true, payload: cheats.allowSpecialColourSchemes });
            return true;
        case "cheats.allowTrackPlaceInvalidHeights":
            reply({ success: true, payload: cheats.allowTrackPlaceInvalidHeights });
            return true;
        case "cheats.buildInPauseMode":
            reply({ success: true, payload: cheats.buildInPauseMode });
            return true;
        case "cheats.disableAllBreakdowns":
            reply({ success: true, payload: cheats.disableAllBreakdowns });
            return true;
        case "cheats.disableBrakesFailure":
            reply({ success: true, payload: cheats.disableBrakesFailure });
            return true;
        case "cheats.disableClearanceChecks":
            reply({ success: true, payload: cheats.disableClearanceChecks });
            return true;
        case "cheats.disableLittering":
            reply({ success: true, payload: cheats.disableLittering });
            return true;
        case "cheats.disablePlantAging":
            reply({ success: true, payload: cheats.disablePlantAging });
            return true;
        case "cheats.disableRideValueAging":
            reply({ success: true, payload: cheats.disableRideValueAging });
            return true;
        case "cheats.disableSupportLimits":
            reply({ success: true, payload: cheats.disableSupportLimits });
            return true;
        case "cheats.disableTrainLengthLimit":
            reply({ success: true, payload: cheats.disableTrainLengthLimit });
            return true;
        case "cheats.disableVandalism":
            reply({ success: true, payload: cheats.disableVandalism });
            return true;
        case "cheats.enableAllDrawableTrackPieces":
            reply({ success: true, payload: cheats.enableAllDrawableTrackPieces });
            return true;
        case "cheats.enableChainLiftOnAllTrack":
            reply({ success: true, payload: cheats.enableChainLiftOnAllTrack });
            return true;
        case "cheats.fastLiftHill":
            reply({ success: true, payload: cheats.fastLiftHill });
            return true;
        case "cheats.forcedParkRating":
            reply({ success: true, payload: cheats.forcedParkRating });
            return true;
        case "cheats.freezeWeather":
            reply({ success: true, payload: cheats.freezeWeather });
            return true;
        case "cheats.ignoreResearchStatus":
            reply({ success: true, payload: cheats.ignoreResearchStatus });
            return true;
        case "cheats.ignoreRideIntensity":
            reply({ success: true, payload: cheats.ignoreRideIntensity });
            return true;
        case "cheats.ignoreRidePrice":
            reply({ success: true, payload: cheats.ignoreRidePrice });
            return true;
        case "cheats.neverendingMarketing":
            reply({ success: true, payload: cheats.neverendingMarketing });
            return true;
        case "cheats.makeAllDestructible":
            reply({ success: true, payload: cheats.makeAllDestructible });
            return true;
        case "cheats.sandboxMode":
            reply({ success: true, payload: cheats.sandboxMode });
            return true;
        case "cheats.showAllOperatingModes":
            reply({ success: true, payload: cheats.showAllOperatingModes });
            return true;
        case "cheats.showVehiclesFromOtherTrackTypes":
            reply({ success: true, payload: cheats.showVehiclesFromOtherTrackTypes });
            return true;
        case "cheats.allowRegularPathAsQueue":
            reply({ success: true, payload: cheats.allowRegularPathAsQueue });
            return true;
        case "date":
            reply({ success: true, payload: getDate() });
            return true;
        case "date.ticksElapsed":
            reply({ success: true, payload: date.ticksElapsed });
            return true;
        case "date.monthsElapsed":
            reply({ success: true, payload: date.monthsElapsed });
            return true;
        case "date.yearsElapsed":
            reply({ success: true, payload: date.yearsElapsed });
            return true;
        case "date.monthProgress":
            reply({ success: true, payload: date.monthProgress });
            return true;
        case "date.day":
            reply({ success: true, payload: date.day });
            return true;
        case "date.month":
            reply({ success: true, payload: date.month });
            return true;
        case "date.year":
            reply({ success: true, payload: date.year });
            return true;
        case "scenario":
            reply({ success: true, payload: getScenario() });
            return true;
        case "scenario.name":
            reply({ success: true, payload: scenario.name });
            return true;
        case "scenario.details":
            reply({ success: true, payload: scenario.details });
            return true;
        case "scenario.completedBy":
            reply({ success: true, payload: scenario.completedBy });
            return true;
        case "scenario.filename":
            reply({ success: true, payload: scenario.filename });
            return true;
        case "scenario.objective":
            reply({ success: true, payload: getScenarioObjective() });
            return true;
        case "scenario.parkRatingWarningDays":
            reply({ success: true, payload: scenario.parkRatingWarningDays });
            return true;
        case "scenario.completedCompanyValue":
            reply({ success: true, payload: scenario.completedCompanyValue !== undefined ? scenario.completedCompanyValue : null });
            return true;
        case "scenario.status":
            reply({ success: true, payload: scenario.status });
            return true;
        case "scenario.companyValueRecord":
            reply({ success: true, payload: scenario.companyValueRecord });
            return true;
        case "climate":
            reply({ success: true, payload: getClimate() });
            return true;
        case "climate.type":
            reply({ success: true, payload: climate.type });
            return true;
        case "climate.current":
            reply({ success: true, payload: getClimateCurrent() });
            return true;
        case "climate.future":
            reply({ success: true, payload: getClimateFuture() });
            return true;
        default:
            return false;
    }
}
